// This package provides functions to interact with the MongoDB database,
// it can implement other database operations as needed, better with an API REST interface.
// It uses the official MongoDB Go driver to perform these operations and handles the context for database operations.
package database

import (
	"log"

	"context"

	"github.com/LoSquadrato/crawltrip/internal/classificator"
	"github.com/LoSquadrato/crawltrip/internal/config"

	"go.mongodb.org/mongo-driver/v2/mongo"
)

// SaveRequest saves a RawRequest to the MongoDB database. idObject is generated by MongoDB and returned in the InsertOneResult
// because of the "container of raw data" nature of this database.
func SaveRequest(ctx context.Context, client *mongo.Client, rawreq classificator.RawRequest) error {
	log.Println("Saving request to database")
	res, err := client.Database(config.DbName).Collection(config.DbCollection).InsertOne(ctx, rawreq)
	if err != nil {
		return err
	}
	log.Printf("Request saved with id: %v\n", res.InsertedID)
	return nil
}
